version: '3'
services:
  app:
    build: app
    restart: always
    ports:
      - "3940:80"
    environment:
      DOCKERIZED: 1

  db:
    image: postgres
    restart: always
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: collage
      POSTGRES_PASSWORD: collage